---
name: iris-erp-backend-api-dev
services:
    app:
        container_name: iris-erp-backend-api-dev-c
        image: iris-erp-backend-api-dev-i
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./src:/app/src
        ports:
            - '3054:3000'
    db:
        container_name: iris-erp-backend-db-dev-c
        image: postgres:16
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: examplepassword
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 3055:5432
volumes:
    pgdata:
