FROM node:21-alpine

# This is the directory "inside" the container
WORKDIR /app

# Copying necessary files
COPY package.json .
COPY yarn.lock .
COPY tsconfig.json .
COPY nodemon.json .
COPY .env .

# Installing node modules
RUN yarn install

# Expose port
EXPOSE 3000

# Starting the server
CMD ["yarn", "run", "dev"]
